In [2]:
import numpy as np

 

# Sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

 

def sigmoid_derivative(x):
    return x * (1 - x)

 

# Input data (AND gate truth table)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

 

# Target output for AND gate
Y = np.array([[0], [0], [0], [1]])

 

# Initialize weights and biases for the neural network
input_layer_neurons = X.shape[1]  # Number of features in the input layer
hidden_layer_neurons = 2  # Number of neurons in the hidden layer
output_neurons = 1  # Number of neurons in the output layer

 

# Initialize weights randomly with mean 0
weights_input_hidden = np.random.uniform(size=(input_layer_neurons, hidden_layer_neurons))
weights_hidden_output = np.random.uniform(size=(hidden_layer_neurons, output_neurons))

 

# Initialize biases randomly with mean 0
bias_hidden = np.random.uniform(size=(1, hidden_layer_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

 

# Learning rate
learning_rate = 0.05

 

# Number of epochs for training
epochs = 10000

 

# Training the neural network
for epoch in range(epochs):
    # Forward propagation
    hidden_layer_activation = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_activation)

 

    output_layer_activation = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_activation)

 

    # Compute error
    error = Y - predicted_output

 

    # Backpropagation
    d_predicted_output = error * sigmoid_derivative(predicted_output)
    error_hidden_layer = d_predicted_output.dot(weights_hidden_output.T)
    d_hidden_layer = error_hidden_layer * sigmoid_derivative(hidden_layer_output)

 

    # Update weights and biases
    weights_hidden_output += hidden_layer_output.T.dot(d_predicted_output) * learning_rate
    weights_input_hidden += X.T.dot(d_hidden_layer) * learning_rate

 

    bias_output += np.sum(d_predicted_output, axis=0, keepdims=True) * learning_rate
    bias_hidden += np.sum(d_hidden_layer, axis=0, keepdims=True) * learning_rate

# Print the final predicted output after training
print("Predicted output after training:")
print(predicted_output)

 

# Print the final weights and biases
print("\nFinal weights (input to hidden):")
print(weights_input_hidden)
print("\nFinal weights (hidden to output):")
print(weights_hidden_output)
print("\nFinal biases (hidden layer):")
print(bias_hidden)
print("\nFinal biases (output layer):")
print(bias_output)



Predicted output after training:
[[0.01730005]
 [0.05629796]
 [0.05645922]
 [0.92547917]]

Final weights (input to hidden):
[[0.38043328 3.46655582]
 [0.50627358 3.47187755]]

Final weights (hidden to output):
[[-0.4187654 ]
 [ 7.68462693]]

Final biases (hidden layer):
[[ 0.87056386 -5.05574089]]

Final biases (output layer):
[[-3.79316477]]


In [4]:
import numpy as np

 

# Input data (AND gate truth table)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

 

# Target output for AND gate
Y = np.array([[1, 0], [1, 0], [1, 0], [0, 1]])

 

# Calculate the pseudo-inverse of the input data
X_pseudo_inverse = np.linalg.pinv(X)

 

# Calculate the weights using the pseudo-inverse method
weights_pseudo_inverse = X_pseudo_inverse.dot(Y)

 

# Print the weights obtained using the pseudo-inverse method
print("Weights obtained using pseudo-inverse:")
print(weights_pseudo_inverse)

 

# Calculate predicted outputs using the weights obtained from the pseudo-inverse
predicted_output_pseudo_inverse = X.dot(weights_pseudo_inverse)

 

# Print the predicted outputs using the pseudo-inverse method
print("\nPredicted output using pseudo-inverse:")
print(predicted_output_pseudo_inverse)



Weights obtained using pseudo-inverse:
[[0.33333333 0.33333333]
 [0.33333333 0.33333333]]

Predicted output using pseudo-inverse:
[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]]


In [5]:
# Predicted outputs obtained from the perceptron learning approach
predicted_output_perceptron = predicted_output

 

# Compare the predicted outputs from both approaches
print("\nComparison of Predicted Outputs:")
print("Predicted output using perceptron learning:")
print(predicted_output_perceptron)
print("\nPredicted output using pseudo-inverse:")
print(predicted_output_pseudo_inverse)


Comparison of Predicted Outputs:
Predicted output using perceptron learning:
[[0.01730005]
 [0.05629796]
 [0.05645922]
 [0.92547917]]

Predicted output using pseudo-inverse:
[[0.         0.        ]
 [0.33333333 0.33333333]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]]
